// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Config documents */
interface ConfigDocumentData {
    /**
     * SEO Title field in *Config*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.seo_title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_title: prismicT.KeyTextField;
    /**
     * Seo Description field in *Config*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.seo_description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_description: prismicT.KeyTextField;
    /**
     * Seo Keywords field in *Config*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.seo_keywords
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_keywords: prismicT.KeyTextField;
    /**
     * Seo Image field in *Config*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: config.seo_image
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    seo_image: prismicT.ImageField<never>;
    /**
     * Header Main Menu field in *Config*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: config.header_main_menu[]
     * - **Tab**: Menus
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    header_main_menu: prismicT.GroupField<Simplify<ConfigDocumentDataHeaderMainMenuItem>>;
    /**
     * Header Secondary Menu field in *Config*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: config.header_secondary_menu[]
     * - **Tab**: Menus
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    header_secondary_menu: prismicT.GroupField<Simplify<ConfigDocumentDataHeaderSecondaryMenuItem>>;
    /**
     * Social field in *Config*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: config.social[]
     * - **Tab**: Social
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    social: prismicT.GroupField<Simplify<ConfigDocumentDataSocialItem>>;
    /**
     * Footer Main Menu field in *Config*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: config.footer_main_menu[]
     * - **Tab**: Footer
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    footer_main_menu: prismicT.GroupField<Simplify<ConfigDocumentDataFooterMainMenuItem>>;
    /**
     * Footer Secondary Menu field in *Config*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: config.footer_secondary_menu[]
     * - **Tab**: Footer
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    footer_secondary_menu: prismicT.GroupField<Simplify<ConfigDocumentDataFooterSecondaryMenuItem>>;
}
/**
 * Item in Config → Header Main Menu
 *
 */
export interface ConfigDocumentDataHeaderMainMenuItem {
    /**
     * Label field in *Config → Header Main Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.header_main_menu[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * Url field in *Config → Header Main Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.header_main_menu[].url
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    url: prismicT.KeyTextField;
}
/**
 * Item in Config → Header Secondary Menu
 *
 */
export interface ConfigDocumentDataHeaderSecondaryMenuItem {
    /**
     * Label field in *Config → Header Secondary Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.header_secondary_menu[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * Url field in *Config → Header Secondary Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.header_secondary_menu[].url
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    url: prismicT.KeyTextField;
}
/**
 * Item in Config → Social
 *
 */
export interface ConfigDocumentDataSocialItem {
    /**
     * Network field in *Config → Social*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.social[].network
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    network: prismicT.KeyTextField;
    /**
     * Url field in *Config → Social*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.social[].url
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    url: prismicT.KeyTextField;
}
/**
 * Item in Config → Footer Main Menu
 *
 */
export interface ConfigDocumentDataFooterMainMenuItem {
    /**
     * Label field in *Config → Footer Main Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.footer_main_menu[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * Url field in *Config → Footer Main Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.footer_main_menu[].url
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    url: prismicT.KeyTextField;
}
/**
 * Item in Config → Footer Secondary Menu
 *
 */
export interface ConfigDocumentDataFooterSecondaryMenuItem {
    /**
     * Label field in *Config → Footer Secondary Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.footer_secondary_menu[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * Url field in *Config → Footer Secondary Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: config.footer_secondary_menu[].url
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    url: prismicT.KeyTextField;
}
/**
 * Config document from Prismic
 *
 * - **API ID**: `config`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConfigDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ConfigDocumentData>, "config", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Seo Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.seo_title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_title: prismicT.KeyTextField;
    /**
     * Seo Description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.seo_description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_description: prismicT.KeyTextField;
    /**
     * Seo Keywords field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.seo_keywords
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_keywords: prismicT.KeyTextField;
    /**
     * Seo Image field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.seo_image
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    seo_image: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices1[]
     * - **Tab**: Content
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices1: prismicT.SliceZone<PageDocumentDataSlices1Slice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = never;
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlices1Slice = RichTextSectionSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Translation Strings documents */
interface TranslationStringsDocumentData {
    /**
     * Scroll field in *Translation Strings*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: translation_strings.scroll
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    scroll: prismicT.KeyTextField;
    /**
     * Swipe field in *Translation Strings*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: translation_strings.swipe
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    swipe: prismicT.KeyTextField;
}
/**
 * Translation Strings document from Prismic
 *
 * - **API ID**: `translation_strings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TranslationStringsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TranslationStringsDocumentData>, "translation_strings", Lang>;
export type AllDocumentTypes = ConfigDocument | PageDocument | TranslationStringsDocument;
/**
 * Primary content in RichTextSection → Primary
 *
 */
interface RichTextSectionSliceDefaultPrimary {
    /**
     * Spacing field in *RichTextSection → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: default
     * - **API ID Path**: rich_text_section.primary.spacing
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    spacing: prismicT.SelectField<"default" | "sm" | "lg", "filled">;
    /**
     * ColSize field in *RichTextSection → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: rich_text_section.primary.colSize
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    colSize: prismicT.NumberField;
    /**
     * Heading field in *RichTextSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: rich_text_section.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heading: prismicT.KeyTextField;
    /**
     * Text field in *RichTextSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: rich_text_section.primary.text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Default variation for RichTextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `RichTextSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RichTextSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<RichTextSectionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *RichTextSection*
 *
 */
type RichTextSectionSliceVariation = RichTextSectionSliceDefault;
/**
 * RichTextSection Shared Slice
 *
 * - **API ID**: `rich_text_section`
 * - **Description**: `RichTextSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RichTextSectionSlice = prismicT.SharedSlice<"rich_text_section", RichTextSectionSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ConfigDocumentData, ConfigDocumentDataHeaderMainMenuItem, ConfigDocumentDataHeaderSecondaryMenuItem, ConfigDocumentDataSocialItem, ConfigDocumentDataFooterMainMenuItem, ConfigDocumentDataFooterSecondaryMenuItem, ConfigDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocumentDataSlices1Slice, PageDocument, TranslationStringsDocumentData, TranslationStringsDocument, AllDocumentTypes, RichTextSectionSliceDefaultPrimary, RichTextSectionSliceDefault, RichTextSectionSliceVariation, RichTextSectionSlice };
    }
}
